import { Node } from '../types';

/**
 * Demo mock data specifically designed to showcase the grouping functionality
 * This data includes:
 * - Multiple button variants (different styles and with/without icons)
 * - Cards with and without badges
 * - Various other components to test grouping behavior
 */
export const groupingDemoMockData: Node = {
  id: '1',
  x: 0,
  y: 0,
  name: 'Grouping Demo Container',
  type: 'Div',
  width: 1200,
  height: 1000,
  background: '#f8fafc',
  padding: '24px',
  children: [
    // Header section
    {
      id: 'header',
      x: 24,
      y: 24,
      name: 'Demo Header',
      type: 'Div',
      width: 1152,
      height: 80,
      background: '#1e293b',
      color: '#ffffff',
      text: 'Component Grouping Demo',
      padding: '24px',
      'font-size': '28px',
      'font-weight': '700',
      'border-radius': '12px',
      children: [],
    },

    // Button Variants Section
    {
      id: 'button-section',
      x: 24,
      y: 124,
      name: 'Button Variants Section',
      type: 'Div',
      width: 1152,
      height: 200,
      background: '#ffffff',
      border: '1px solid #e2e8f0',
      'border-radius': '8px',
      padding: '20px',
      children: [
        // Section title
        {
          id: 'button-title',
          x: 44,
          y: 144,
          name: 'Button Section Title',
          type: 'Div',
          width: 300,
          height: 30,
          color: '#1e293b',
          text: 'Button Variants (Should Group Together)',
          'font-size': '18px',
          'font-weight': '600',
          children: [],
        },

        // Primary buttons without icons
        {
          id: 'btn-primary-1',
          x: 44,
          y: 190,
          name: 'Primary Button 1',
          type: 'Button',
          width: 120,
          height: 40,
          background: '#3b82f6',
          color: '#ffffff',
          text: 'Save',
          'border-radius': '6px',
          border: 'none',
          'font-size': '14px',
          'font-weight': '500',
          children: [],
        },
        {
          id: 'btn-primary-2',
          x: 184,
          y: 190,
          name: 'Primary Button 2',
          type: 'Button',
          width: 120,
          height: 40,
          background: '#3b82f6',
          color: '#ffffff',
          text: 'Submit',
          'border-radius': '6px',
          border: 'none',
          'font-size': '14px',
          'font-weight': '500',
          children: [],
        },

        // Primary buttons with icons
        {
          id: 'btn-primary-icon-1',
          x: 324,
          y: 190,
          name: 'Primary Button with Icon 1',
          type: 'Button',
          width: 140,
          height: 40,
          background: '#3b82f6',
          color: '#ffffff',
          text: 'Download',
          'border-radius': '6px',
          border: 'none',
          'font-size': '14px',
          'font-weight': '500',
          children: [
            {
              id: 'icon-download',
              x: 334,
              y: 200,
              name: 'Download Icon',
              type: 'Image',
              width: 16,
              height: 16,
              src: 'download-icon.svg',
              alt: 'Download',
              children: [],
            },
          ],
        },
        {
          id: 'btn-primary-icon-2',
          x: 484,
          y: 190,
          name: 'Primary Button with Icon 2',
          type: 'Button',
          width: 140,
          height: 40,
          background: '#3b82f6',
          color: '#ffffff',
          text: 'Upload',
          'border-radius': '6px',
          border: 'none',
          'font-size': '14px',
          'font-weight': '500',
          children: [
            {
              id: 'icon-upload',
              x: 494,
              y: 200,
              name: 'Upload Icon',
              type: 'Image',
              width: 16,
              height: 16,
              src: 'upload-icon.svg',
              alt: 'Upload',
              children: [],
            },
          ],
        },

        // Secondary buttons
        {
          id: 'btn-secondary-1',
          x: 644,
          y: 190,
          name: 'Secondary Button 1',
          type: 'Button',
          width: 120,
          height: 40,
          background: '#6b7280',
          color: '#ffffff',
          text: 'Cancel',
          'border-radius': '6px',
          border: 'none',
          'font-size': '14px',
          'font-weight': '500',
          children: [],
        },
        {
          id: 'btn-secondary-2',
          x: 784,
          y: 190,
          name: 'Secondary Button 2',
          type: 'Button',
          width: 120,
          height: 40,
          background: '#6b7280',
          color: '#ffffff',
          text: 'Close',
          'border-radius': '6px',
          border: 'none',
          'font-size': '14px',
          'font-weight': '500',
          children: [],
        },

        // Danger buttons
        {
          id: 'btn-danger-1',
          x: 924,
          y: 190,
          name: 'Danger Button 1',
          type: 'Button',
          width: 120,
          height: 40,
          background: '#dc2626',
          color: '#ffffff',
          text: 'Delete',
          'border-radius': '6px',
          border: 'none',
          'font-size': '14px',
          'font-weight': '500',
          children: [],
        },

        // Outline buttons
        {
          id: 'btn-outline-1',
          x: 44,
          y: 250,
          name: 'Outline Button 1',
          type: 'Button',
          width: 120,
          height: 40,
          background: 'transparent',
          color: '#3b82f6',
          text: 'Learn More',
          'border-radius': '6px',
          border: '2px solid #3b82f6',
          'font-size': '14px',
          'font-weight': '500',
          children: [],
        },
        {
          id: 'btn-outline-2',
          x: 184,
          y: 250,
          name: 'Outline Button 2',
          type: 'Button',
          width: 120,
          height: 40,
          background: 'transparent',
          color: '#3b82f6',
          text: 'View Details',
          'border-radius': '6px',
          border: '2px solid #3b82f6',
          'font-size': '14px',
          'font-weight': '500',
          children: [],
        },
      ],
    },

    // Card Section with and without badges
    {
      id: 'card-section',
      x: 24,
      y: 344,
      name: 'Card Section',
      type: 'Div',
      width: 1152,
      height: 400,
      background: '#ffffff',
      border: '1px solid #e2e8f0',
      'border-radius': '8px',
      padding: '20px',
      children: [
        // Section title
        {
          id: 'card-title',
          x: 44,
          y: 364,
          name: 'Card Section Title',
          type: 'Div',
          width: 400,
          height: 30,
          color: '#1e293b',
          text: 'Product Cards (With and Without Badges)',
          'font-size': '18px',
          'font-weight': '600',
          children: [],
        },

        // Cards without badges
        {
          id: 'card-no-badge-1',
          x: 44,
          y: 410,
          name: 'Product Card 1',
          type: 'Div',
          width: 250,
          height: 300,
          background: '#ffffff',
          border: '1px solid #e2e8f0',
          'border-radius': '8px',
          'box-shadow': '0 2px 4px rgba(0,0,0,0.1)',
          padding: '16px',
          children: [
            {
              id: 'card-1-image',
              x: 60,
              y: 426,
              name: 'Product Image 1',
              type: 'Image',
              width: 218,
              height: 120,
              background: '#f1f5f9',
              'border-radius': '6px',
              src: 'product-1.jpg',
              alt: 'Product 1',
              children: [],
            },
            {
              id: 'card-1-title',
              x: 60,
              y: 566,
              name: 'Product Title 1',
              type: 'Div',
              width: 218,
              height: 50,
              color: '#1e293b',
              text: 'Premium Headphones',
              'font-size': '16px',
              'font-weight': '600',
              'line-height': '1.5',
              children: [],
            },
            {
              id: 'card-1-description',
              x: 60,
              y: 626,
              name: 'Product Description 1',
              type: 'Div',
              width: 218,
              height: 40,
              color: '#64748b',
              text: 'High-quality wireless headphones with noise cancellation.',
              'font-size': '14px',
              'line-height': '1.4',
              children: [],
            },
            {
              id: 'card-1-price',
              x: 60,
              y: 676,
              name: 'Product Price 1',
              type: 'Div',
              width: 100,
              height: 24,
              color: '#059669',
              text: '$199.99',
              'font-size': '18px',
              'font-weight': '700',
              children: [],
            },
          ],
        },

        {
          id: 'card-no-badge-2',
          x: 314,
          y: 410,
          name: 'Product Card 2',
          type: 'Div',
          width: 250,
          height: 300,
          background: '#ffffff',
          border: '1px solid #e2e8f0',
          'border-radius': '8px',
          'box-shadow': '0 2px 4px rgba(0,0,0,0.1)',
          padding: '16px',
          children: [
            {
              id: 'card-2-image',
              x: 330,
              y: 426,
              name: 'Product Image 2',
              type: 'Image',
              width: 218,
              height: 120,
              background: '#f1f5f9',
              'border-radius': '6px',
              src: 'product-2.jpg',
              alt: 'Product 2',
              children: [],
            },
            {
              id: 'card-2-title',
              x: 330,
              y: 566,
              name: 'Product Title 2',
              type: 'Div',
              width: 218,
              height: 50,
              color: '#1e293b',
              text: 'Gaming Mouse',
              'font-size': '16px',
              'font-weight': '600',
              'line-height': '1.5',
              children: [],
            },
            {
              id: 'card-2-description',
              x: 330,
              y: 626,
              name: 'Product Description 2',
              type: 'Div',
              width: 218,
              height: 40,
              color: '#64748b',
              text: 'Precision gaming mouse with RGB lighting.',
              'font-size': '14px',
              'line-height': '1.4',
              children: [],
            },
            {
              id: 'card-2-price',
              x: 330,
              y: 676,
              name: 'Product Price 2',
              type: 'Div',
              width: 100,
              height: 24,
              color: '#059669',
              text: '$79.99',
              'font-size': '18px',
              'font-weight': '700',
              children: [],
            },
          ],
        },

        // Cards with badges
        {
          id: 'card-with-badge-1',
          x: 584,
          y: 410,
          name: 'Product Card with Badge 1',
          type: 'Div',
          width: 250,
          height: 300,
          background: '#ffffff',
          border: '1px solid #e2e8f0',
          'border-radius': '8px',
          'box-shadow': '0 2px 4px rgba(0,0,0,0.1)',
          padding: '16px',
          children: [
            // Badge (small component that differentiates this card)
            {
              id: 'card-3-badge',
              x: 800,
              y: 420,
              name: 'Sale Badge',
              type: 'Div',
              width: 50,
              height: 24,
              background: '#ef4444',
              color: '#ffffff',
              text: 'SALE',
              'font-size': '10px',
              'font-weight': '700',
              'border-radius': '12px',
              'text-align': 'center',
              'line-height': '24px',
              children: [],
            },
            {
              id: 'card-3-image',
              x: 600,
              y: 426,
              name: 'Product Image 3',
              type: 'Image',
              width: 218,
              height: 120,
              background: '#f1f5f9',
              'border-radius': '6px',
              src: 'product-3.jpg',
              alt: 'Product 3',
              children: [],
            },
            {
              id: 'card-3-title',
              x: 600,
              y: 566,
              name: 'Product Title 3',
              type: 'Div',
              width: 218,
              height: 50,
              color: '#1e293b',
              text: 'Mechanical Keyboard',
              'font-size': '16px',
              'font-weight': '600',
              'line-height': '1.5',
              children: [],
            },
            {
              id: 'card-3-description',
              x: 600,
              y: 626,
              name: 'Product Description 3',
              type: 'Div',
              width: 218,
              height: 40,
              color: '#64748b',
              text: 'Premium mechanical keyboard with blue switches.',
              'font-size': '14px',
              'line-height': '1.4',
              children: [],
            },
            {
              id: 'card-3-price',
              x: 600,
              y: 676,
              name: 'Product Price 3',
              type: 'Div',
              width: 100,
              height: 24,
              color: '#059669',
              text: '$149.99',
              'font-size': '18px',
              'font-weight': '700',
              children: [],
            },
          ],
        },

        {
          id: 'card-with-badge-2',
          x: 854,
          y: 410,
          name: 'Product Card with Badge 2',
          type: 'Div',
          width: 250,
          height: 300,
          background: '#ffffff',
          border: '1px solid #e2e8f0',
          'border-radius': '8px',
          'box-shadow': '0 2px 4px rgba(0,0,0,0.1)',
          padding: '16px',
          children: [
            // Badge (small component that differentiates this card)
            {
              id: 'card-4-badge',
              x: 1070,
              y: 420,
              name: 'New Badge',
              type: 'Div',
              width: 50,
              height: 24,
              background: '#22c55e',
              color: '#ffffff',
              text: 'NEW',
              'font-size': '10px',
              'font-weight': '700',
              'border-radius': '12px',
              'text-align': 'center',
              'line-height': '24px',
              children: [],
            },
            {
              id: 'card-4-image',
              x: 870,
              y: 426,
              name: 'Product Image 4',
              type: 'Image',
              width: 218,
              height: 120,
              background: '#f1f5f9',
              'border-radius': '6px',
              src: 'product-4.jpg',
              alt: 'Product 4',
              children: [],
            },
            {
              id: 'card-4-title',
              x: 870,
              y: 566,
              name: 'Product Title 4',
              type: 'Div',
              width: 218,
              height: 50,
              color: '#1e293b',
              text: 'Webcam HD',
              'font-size': '16px',
              'font-weight': '600',
              'line-height': '1.5',
              children: [],
            },
            {
              id: 'card-4-description',
              x: 870,
              y: 626,
              name: 'Product Description 4',
              type: 'Div',
              width: 218,
              height: 40,
              color: '#64748b',
              text: '1080p webcam with auto-focus and built-in microphone.',
              'font-size': '14px',
              'line-height': '1.4',
              children: [],
            },
            {
              id: 'card-4-price',
              x: 870,
              y: 676,
              name: 'Product Price 4',
              type: 'Div',
              width: 100,
              height: 24,
              color: '#059669',
              text: '$89.99',
              'font-size': '18px',
              'font-weight': '700',
              children: [],
            },
          ],
        },
      ],
    },

    // Mixed Component Section
    {
      id: 'mixed-section',
      x: 24,
      y: 764,
      name: 'Mixed Components Section',
      type: 'Div',
      width: 1152,
      height: 200,
      background: '#ffffff',
      border: '1px solid #e2e8f0',
      'border-radius': '8px',
      padding: '20px',
      children: [
        {
          id: 'mixed-title',
          x: 44,
          y: 784,
          name: 'Mixed Section Title',
          type: 'Div',
          width: 300,
          height: 30,
          color: '#1e293b',
          text: 'Mixed Components (Different Types)',
          'font-size': '18px',
          'font-weight': '600',
          children: [],
        },

        // Input fields (should group together)
        {
          id: 'input-email',
          x: 44,
          y: 830,
          name: 'Email Input',
          type: 'Input',
          width: 200,
          height: 40,
          background: '#ffffff',
          border: '2px solid #d1d5db',
          'border-radius': '6px',
          placeholder: 'Enter your email',
          children: [],
        },
        {
          id: 'input-password',
          x: 264,
          y: 830,
          name: 'Password Input',
          type: 'Input',
          width: 200,
          height: 40,
          background: '#ffffff',
          border: '2px solid #d1d5db',
          'border-radius': '6px',
          placeholder: 'Enter your password',
          children: [],
        },

        // Images (should group together)
        {
          id: 'avatar-1',
          x: 484,
          y: 830,
          name: 'User Avatar 1',
          type: 'Image',
          width: 40,
          height: 40,
          background: '#e5e7eb',
          'border-radius': '50%',
          src: 'avatar-1.jpg',
          alt: 'User 1',
          children: [],
        },
        {
          id: 'avatar-2',
          x: 544,
          y: 830,
          name: 'User Avatar 2',
          type: 'Image',
          width: 40,
          height: 40,
          background: '#e5e7eb',
          'border-radius': '50%',
          src: 'avatar-2.jpg',
          alt: 'User 2',
          children: [],
        },
        {
          id: 'avatar-3',
          x: 604,
          y: 830,
          name: 'User Avatar 3',
          type: 'Image',
          width: 40,
          height: 40,
          background: '#e5e7eb',
          'border-radius': '50%',
          src: 'avatar-3.jpg',
          alt: 'User 3',
          children: [],
        },

        // Status indicators (should group together)
        {
          id: 'status-online',
          x: 664,
          y: 830,
          name: 'Online Status',
          type: 'Div',
          width: 80,
          height: 40,
          background: '#22c55e',
          color: '#ffffff',
          text: 'Online',
          'border-radius': '20px',
          'font-size': '12px',
          'font-weight': '500',
          'text-align': 'center',
          'line-height': '40px',
          children: [],
        },
        {
          id: 'status-offline',
          x: 764,
          y: 830,
          name: 'Offline Status',
          type: 'Div',
          width: 80,
          height: 40,
          background: '#ef4444',
          color: '#ffffff',
          text: 'Offline',
          'border-radius': '20px',
          'font-size': '12px',
          'font-weight': '500',
          'text-align': 'center',
          'line-height': '40px',
          children: [],
        },
        {
          id: 'status-away',
          x: 864,
          y: 830,
          name: 'Away Status',
          type: 'Div',
          width: 80,
          height: 40,
          background: '#f59e0b',
          color: '#ffffff',
          text: 'Away',
          'border-radius': '20px',
          'font-size': '12px',
          'font-weight': '500',
          'text-align': 'center',
          'line-height': '40px',
          children: [],
        },
      ],
    },
  ],
};

/**
 * Expected grouping results for this demo data:
 *
 * Button Groups:
 * - Primary Buttons (4 total: 2 without icons, 2 with icons)
 *   - Variations: "Without Icon" (2), "With Icon" (2)
 * - Secondary Buttons (2 total)
 * - Danger Buttons (1 total - won't group as needs minimum 2)
 * - Outline Buttons (2 total)
 *
 * Card Groups:
 * - Product Cards (4 total: 2 without badges, 2 with badges)
 *   - Variations: "Without Badge" (2), "With Badge" (2)
 *
 * Input Groups:
 * - Input Fields (2 total)
 *
 * Image Groups:
 * - User Avatars (3 total)
 *
 * Status Groups:
 * - Status Indicators (3 total - different colors but similar structure)
 */
