import { Node } from '../components/CSSInspector';

// Original mock data for testing (keeping original structure for initial conversion)
export const originalMockData: Node = {
  id: '1',
  x: 0,
  y: 0,
  name: 'Root Container',
  type: 'Div',
  width: 800,
  height: 600,
  background: '#f5f5f5',
  children: [
    {
      id: '2',
      x: 50,
      y: 50,
      name: 'Header',
      type: 'Div',
      width: 700,
      height: 80,
      background: '#3b82f6',
      color: '#ffffff',
      text: 'Header Content',
      children: [
        {
          id: '3',
          x: 70,
          y: 70,
          name: 'Logo',
          type: 'Image',
          width: 60,
          height: 40,
          background: '#ffffff',
          children: [],
        },
        {
          id: '4',
          x: 600,
          y: 65,
          name: 'Login Button',
          type: 'Button',
          width: 100,
          height: 35,
          background: '#10b981',
          color: '#ffffff',
          text: 'Login',
          border: '1px solid #059669',
          children: [],
        },
      ],
    },
    {
      id: '5',
      x: 50,
      y: 150,
      name: 'Main Content',
      type: 'Div',
      width: 700,
      height: 400,
      background: '#ffffff',
      border: '1px solid #e5e7eb',
      children: [
        {
          id: '6',
          x: 100,
          y: 200,
          name: 'Search Input',
          type: 'Input',
          width: 300,
          height: 40,
          background: '#ffffff',
          border: '2px solid #d1d5db',
          children: [],
        },
        {
          id: '7',
          x: 420,
          y: 200,
          name: 'Search Button',
          type: 'Button',
          width: 80,
          height: 40,
          background: '#3b82f6',
          color: '#ffffff',
          text: 'Search',
          children: [],
        },
        {
          id: '8',
          x: 100,
          y: 280,
          name: 'Card Container',
          type: 'Div',
          width: 600,
          height: 250,
          background: '#f9fafb',
          border: '1px solid #e5e7eb',
          children: [
            {
              id: '9',
              x: 120,
              y: 300,
              name: 'Card 1',
              type: 'Div',
              width: 180,
              height: 200,
              background: '#ffffff',
              border: '1px solid #d1d5db',
              children: [],
            },
            {
              id: '10',
              x: 320,
              y: 300,
              name: 'Card 2',
              type: 'Div',
              width: 180,
              height: 200,
              background: '#ffffff',
              border: '1px solid #d1d5db',
              children: [],
            },
            {
              id: '11',
              x: 520,
              y: 300,
              name: 'Card 3',
              type: 'Div',
              width: 180,
              height: 200,
              background: '#ffffff',
              border: '1px solid #d1d5db',
              children: [],
            },
          ],
        },
      ],
    },
  ],
};

// New mock data matching the screenshot UI layout
export const screenshotMockData: Node = {
  id: '1',
  x: 0,
  y: 0,
  name: 'Root Container',
  type: 'Div',
  width: 420,
  height: 600,
  background: '#f8f9fa',
  padding: '20px',
  children: [
    {
      id: '2',
      x: 20,
      y: 20,
      name: 'Header',
      type: 'Div',
      width: 100,
      height: 60,
      color: '#1f2937',
      text: 'Header',
      padding: '20px',
      'font-size': '24px',
      'font-weight': '700',
      children: [],
    },
    {
      id: '3',
      x: 20,
      y: 100,
      name: 'Text 2',
      type: 'Div',
      width: 380,
      height: 60,
      background: '#fbbf24',
      color: '#1f2937',
      text: 'Text 2',
      'border-radius': '8px',
      padding: '20px',
      'font-size': '16px',
      'font-weight': '500',
      children: [],
    },
    {
      id: '4',
      x: 20,
      y: 180,
      name: 'Section Container 1',
      type: 'Div',
      width: 380,
      height: 140,
      background: '#10b981',
      'border-radius': '8px',
      padding: '20px',
      children: [
        {
          id: '5',
          x: 40,
          y: 200,
          name: 'Button 1',
          type: 'Button',
          width: 340,
          height: 40,
          background: '#3b82f6',
          color: '#ffffff',
          text: 'Button 1',
          'border-radius': '6px',
          border: 'none',
          'font-size': '14px',
          'font-weight': '500',
          children: [],
        },
        {
          id: '6',
          x: 40,
          y: 260,
          name: 'Image 1',
          type: 'Image',
          width: 340,
          height: 40,
          background: '#c084fc',
          'border-radius': '6px',
          children: [],
        },
      ],
    },
    {
      id: '7',
      x: 20,
      y: 340,
      name: 'Section Container 2',
      type: 'Div',
      width: 380,
      height: 140,
      background: '#10b981',
      'border-radius': '8px',
      padding: '20px',
      children: [
        {
          id: '8',
          x: 40,
          y: 360,
          name: 'Button 2',
          type: 'Button',
          width: 340,
          height: 40,
          background: '#3b82f6',
          color: '#ffffff',
          text: 'Button 2',
          'border-radius': '6px',
          border: 'none',
          'font-size': '14px',
          'font-weight': '500',
          children: [],
        },
        {
          id: '9',
          x: 40,
          y: 420,
          name: 'Image 2',
          type: 'Image',
          width: 340,
          height: 40,
          background: '#c084fc',
          'border-radius': '6px',
          children: [],
        },
      ],
    },
  ],
};

// Default mock data (can be switched between original and screenshot layouts)
export const mockData = screenshotMockData;
