import { Node } from '../components/CSSInspector';

// Original mock data for testing (keeping original structure for initial conversion)
export const originalMockData: Node = {
  id: '1',
  x: 0,
  y: 0,
  name: 'Root Container',
  type: 'Div',
  width: 800,
  height: 600,
  background: '#f5f5f5',
  children: [
    {
      id: '2',
      x: 50,
      y: 50,
      name: 'Header',
      type: 'Div',
      width: 700,
      height: 80,
      background: '#3b82f6',
      color: '#ffffff',
      text: 'Header Content',
      children: [
        {
          id: '3',
          x: 70,
          y: 70,
          name: 'Logo',
          type: 'Image',
          width: 60,
          height: 40,
          background: '#ffffff',
          children: [],
        },
        {
          id: '4',
          x: 600,
          y: 65,
          name: 'Login Button',
          type: 'Button',
          width: 100,
          height: 35,
          background: '#10b981',
          color: '#ffffff',
          text: 'Login',
          border: '1px solid #059669',
          children: [],
        },
      ],
    },
    {
      id: '5',
      x: 50,
      y: 150,
      name: 'Main Content',
      type: 'Div',
      width: 700,
      height: 400,
      background: '#ffffff',
      border: '1px solid #e5e7eb',
      children: [
        {
          id: '6',
          x: 100,
          y: 200,
          name: 'Search Input',
          type: 'Input',
          width: 300,
          height: 40,
          background: '#ffffff',
          border: '2px solid #d1d5db',
          children: [],
        },
        {
          id: '7',
          x: 420,
          y: 200,
          name: 'Search Button',
          type: 'Button',
          width: 80,
          height: 40,
          background: '#3b82f6',
          color: '#ffffff',
          text: 'Search',
          children: [],
        },
        {
          id: '8',
          x: 100,
          y: 280,
          name: 'Card Container',
          type: 'Div',
          width: 600,
          height: 250,
          background: '#f9fafb',
          border: '1px solid #e5e7eb',
          children: [
            {
              id: '9',
              x: 120,
              y: 300,
              name: 'Card 1',
              type: 'Div',
              width: 180,
              height: 200,
              background: '#ffffff',
              border: '1px solid #d1d5db',
              children: [],
            },
            {
              id: '10',
              x: 320,
              y: 300,
              name: 'Card 2',
              type: 'Div',
              width: 180,
              height: 200,
              background: '#ffffff',
              border: '1px solid #d1d5db',
              children: [],
            },
            {
              id: '11',
              x: 520,
              y: 300,
              name: 'Card 3',
              type: 'Div',
              width: 180,
              height: 200,
              background: '#ffffff',
              border: '1px solid #d1d5db',
              children: [],
            },
          ],
        },
      ],
    },
  ],
};

// New mock data matching the screenshot UI layout
export const screenshotMockData: Node = {
  id: '1',
  x: 0,
  y: 0,
  name: 'Root Container',
  type: 'Div',
  width: 420,
  height: 600,
  background: '#f8f9fa',
  padding: '20px',
  children: [
    {
      id: '2',
      x: 20,
      y: 20,
      name: 'Header',
      type: 'Div',
      width: 100,
      height: 60,
      color: '#1f2937',
      text: 'Header',
      padding: '20px',
      'font-size': '24px',
      'font-weight': '700',
      children: [],
    },
    {
      id: '3',
      x: 20,
      y: 100,
      name: 'Text 2',
      type: 'Div',
      width: 380,
      height: 60,
      background: '#fbbf24',
      color: '#1f2937',
      text: 'Text 2',
      'border-radius': '8px',
      padding: '20px',
      'font-size': '16px',
      'font-weight': '500',
      children: [],
    },
    {
      id: '4',
      x: 20,
      y: 180,
      name: 'Section Container 1',
      type: 'Div',
      width: 380,
      height: 140,
      background: '#10b981',
      'border-radius': '8px',
      padding: '20px',
      children: [
        {
          id: '5',
          x: 40,
          y: 200,
          name: 'Button 1',
          type: 'Button',
          width: 340,
          height: 40,
          background: '#3b82f6',
          color: '#ffffff',
          text: 'Button 1',
          'border-radius': '6px',
          border: 'none',
          'font-size': '14px',
          'font-weight': '500',
          children: [],
        },
        {
          id: '6',
          x: 40,
          y: 260,
          name: 'Image 1',
          type: 'Image',
          width: 340,
          height: 40,
          background: '#c084fc',
          'border-radius': '6px',
          children: [],
        },
      ],
    },
    {
      id: '7',
      x: 20,
      y: 340,
      name: 'Section Container 2',
      type: 'Div',
      width: 380,
      height: 140,
      background: '#10b981',
      'border-radius': '8px',
      padding: '20px',
      children: [
        {
          id: '8',
          x: 40,
          y: 360,
          name: 'Button 2',
          type: 'Button',
          width: 340,
          height: 40,
          background: '#3b82f6',
          color: '#ffffff',
          text: 'Button 2',
          'border-radius': '6px',
          border: 'none',
          'font-size': '14px',
          'font-weight': '500',
          children: [],
        },
        {
          id: '9',
          x: 40,
          y: 420,
          name: 'Image 2',
          type: 'Image',
          width: 340,
          height: 40,
          background: '#c084fc',
          'border-radius': '6px',
          children: [],
        },
      ],
    },
  ],
};

// Performance test configurations
export const stressTestMockData: Node = {
  id: '1',
  x: 0,
  y: 0,
  name: 'Root Container',
  type: 'Div',
  width: 1200,
  height: 2000,
  background: '#f8f9fa',
  padding: '20px',
  children: [
    // Header section
    {
      id: '2',
      x: 20,
      y: 20,
      name: 'Header',
      type: 'Div',
      width: 1160,
      height: 80,
      background: '#1f2937',
      color: '#ffffff',
      text: 'Application Header',
      padding: '20px',
      'font-size': '24px',
      'font-weight': '700',
      children: [],
    },
    // Navigation bar with repeated nav items
    {
      id: '3',
      x: 20,
      y: 120,
      name: 'Navigation Bar',
      type: 'Div',
      width: 1160,
      height: 60,
      background: '#374151',
      display: 'flex',
      'align-items': 'center',
      gap: '20px',
      padding: '0 20px',
      children: Array.from({ length: 8 }, (_, i) => ({
        id: `nav-${i + 4}`,
        x: 40 + i * 140,
        y: 135,
        name: `Nav Item ${i + 1}`,
        type: 'Button' as const,
        width: 120,
        height: 30,
        background: '#6b7280',
        color: '#ffffff',
        text: `Nav ${i + 1}`,
        'border-radius': '4px',
        border: 'none',
        'font-size': '14px',
        children: [],
      })),
    },
    // Main content area with repeated card components
    {
      id: '12',
      x: 20,
      y: 200,
      name: 'Main Content',
      type: 'Div',
      width: 1160,
      height: 1600,
      background: '#ffffff',
      padding: '20px',
      children: [
        // Grid of product cards (6x5 = 30 cards)
        ...Array.from({ length: 30 }, (_, i) => {
          const row = Math.floor(i / 6);
          const col = i % 6;
          return {
            id: `product-card-${i + 13}`,
            x: 40 + col * 190,
            y: 220 + row * 280,
            name: `Product Card ${i + 1}`,
            type: 'Div' as const,
            width: 180,
            height: 260,
            background: '#ffffff',
            border: '1px solid #e5e7eb',
            'border-radius': '8px',
            'box-shadow': '0 2px 4px rgba(0,0,0,0.1)',
            children: [
              {
                id: `product-image-${i + 43}`,
                x: 50 + col * 190,
                y: 230 + row * 280,
                name: `Product Image ${i + 1}`,
                type: 'Image' as const,
                width: 160,
                height: 120,
                background: '#f3f4f6',
                'border-radius': '6px',
                children: [],
              },
              {
                id: `product-title-${i + 73}`,
                x: 50 + col * 190,
                y: 360 + row * 280,
                name: `Product Title ${i + 1}`,
                type: 'Div' as const,
                width: 160,
                height: 40,
                color: '#1f2937',
                text: `Product ${i + 1}`,
                'font-size': '16px',
                'font-weight': '600',
                padding: '10px',
                children: [],
              },
              {
                id: `product-price-${i + 103}`,
                x: 50 + col * 190,
                y: 410 + row * 280,
                name: `Product Price ${i + 1}`,
                type: 'Div' as const,
                width: 80,
                height: 30,
                color: '#059669',
                text: `$${(i + 1) * 10}`,
                'font-size': '18px',
                'font-weight': '700',
                padding: '5px 10px',
                children: [],
              },
              {
                id: `add-to-cart-${i + 133}`,
                x: 140 + col * 190,
                y: 410 + row * 280,
                name: `Add to Cart ${i + 1}`,
                type: 'Button' as const,
                width: 70,
                height: 30,
                background: '#3b82f6',
                color: '#ffffff',
                text: 'Add',
                'border-radius': '4px',
                border: 'none',
                'font-size': '12px',
                children: [],
              },
            ],
          };
        }),
      ],
    },
    // Sidebar with repeated widget components
    {
      id: '163',
      x: 1200,
      y: 200,
      name: 'Sidebar',
      type: 'Div',
      width: 280,
      height: 1600,
      background: '#f9fafb',
      border: '1px solid #e5e7eb',
      padding: '20px',
      children: [
        // Repeated sidebar widgets
        ...Array.from({ length: 12 }, (_, i) => ({
          id: `sidebar-widget-${i + 164}`,
          x: 1220,
          y: 220 + i * 130,
          name: `Sidebar Widget ${i + 1}`,
          type: 'Div' as const,
          width: 240,
          height: 120,
          background: '#ffffff',
          border: '1px solid #d1d5db',
          'border-radius': '6px',
          padding: '15px',
          children: [
            {
              id: `widget-title-${i + 176}`,
              x: 1235,
              y: 235 + i * 130,
              name: `Widget Title ${i + 1}`,
              type: 'Div' as const,
              width: 210,
              height: 25,
              color: '#374151',
              text: `Widget ${i + 1}`,
              'font-size': '14px',
              'font-weight': '600',
              children: [],
            },
            {
              id: `widget-content-${i + 188}`,
              x: 1235,
              y: 265 + i * 130,
              name: `Widget Content ${i + 1}`,
              type: 'Div' as const,
              width: 210,
              height: 40,
              color: '#6b7280',
              text: `Content for widget ${i + 1}`,
              'font-size': '12px',
              children: [],
            },
            {
              id: `widget-action-${i + 200}`,
              x: 1235,
              y: 310 + i * 130,
              name: `Widget Action ${i + 1}`,
              type: 'Button' as const,
              width: 60,
              height: 25,
              background: '#6b7280',
              color: '#ffffff',
              text: 'Action',
              'border-radius': '4px',
              border: 'none',
              'font-size': '11px',
              children: [],
            },
          ],
        })),
      ],
    },
    // Footer with repeated social media icons
    {
      id: '212',
      x: 20,
      y: 1820,
      name: 'Footer',
      type: 'Div',
      width: 1160,
      height: 160,
      background: '#1f2937',
      color: '#ffffff',
      padding: '40px',
      children: [
        {
          id: '213',
          x: 60,
          y: 1840,
          name: 'Footer Content',
          type: 'Div',
          width: 1080,
          height: 80,
          display: 'flex',
          'justify-content': 'space-between',
          'align-items': 'center',
          children: [
            {
              id: '214',
              x: 60,
              y: 1860,
              name: 'Footer Text',
              type: 'Div',
              width: 300,
              height: 40,
              color: '#d1d5db',
              text: '© 2025 Stress Test App',
              'font-size': '14px',
              children: [],
            },
            // Social media icons (repeated pattern)
            ...Array.from({ length: 6 }, (_, i) => ({
              id: `social-icon-${i + 215}`,
              x: 400 + i * 50,
              y: 1860,
              name: `Social Icon ${i + 1}`,
              type: 'Button' as const,
              width: 40,
              height: 40,
              background: '#374151',
              color: '#ffffff',
              text: `S${i + 1}`,
              'border-radius': '50%',
              border: 'none',
              'font-size': '12px',
              children: [],
            })),
          ],
        },
      ],
    },
  ],
};

// Performance test configurations
export const performanceTestConfig = {
  small: screenshotMockData, // 9 nodes - Basic test
  medium: originalMockData, // 11 nodes - Medium complexity
  large: stressTestMockData, // 221+ nodes - High performance test
};

// Default mock data (can be switched for performance testing)
// Change this to test different scales: 'small', 'medium', 'large'
const testScale: keyof typeof performanceTestConfig = 'large';
export const mockData = performanceTestConfig[testScale];
